//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tourest.Rresource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResHomePage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResHomePage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tourest.Rresource.ResHomePage", typeof(ResHomePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See in egypt.
        /// </summary>
        public static string HomePageblogHeader {
            get {
                return ResourceManager.GetString("HomePageblogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from the blog.
        /// </summary>
        public static string HomePageblogMainHeader {
            get {
                return ResourceManager.GetString("HomePageblogMainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose category.
        /// </summary>
        public static string HomePageCategory {
            get {
                return ResourceManager.GetString("HomePageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose city.
        /// </summary>
        public static string HomePageCity {
            get {
                return ResourceManager.GetString("HomePageCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ve got to see it to believe it in Egypt – the chaos of Cairo (seriously, this city never stops); the bustling bazaars; the imposing glory of the Pyramids of Giza and the world’s most famous lion with a human head (the iconic Sphinx). Only in Egypt can you sail into the sunset on a felucca cruise along the Nile, jump on the back of a camel and ride into Luxor’s Valley of the Kings, then float facing towards the sky in the glittering expanse of the Red Sea. Take a moment as time stands still in Egypt..
        /// </summary>
        public static string HomePageDes {
            get {
                return ResourceManager.GetString("HomePageDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find my tour.
        /// </summary>
        public static string HomePageFindMyTourButton {
            get {
                return ResourceManager.GetString("HomePageFindMyTourButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finden Sie Ihre Tour.
        /// </summary>
        public static string HomePageHeaderButton {
            get {
                return ResourceManager.GetString("HomePageHeaderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen zu YallaToursHurghada.
        /// </summary>
        public static string HomePageHeaderDesc {
            get {
                return ResourceManager.GetString("HomePageHeaderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # instagram.
        /// </summary>
        public static string HomePageInstgramTitel {
            get {
                return ResourceManager.GetString("HomePageInstgramTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aricals Section.
        /// </summary>
        public static string HomePageMainTitelArticals {
            get {
                return ResourceManager.GetString("HomePageMainTitelArticals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max price.
        /// </summary>
        public static string HomePageMaxPrice {
            get {
                return ResourceManager.GetString("HomePageMaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price match within 48 hours of order confirmation.
        /// </summary>
        public static string HomePageMediaBodyFourDesc {
            get {
                return ResourceManager.GetString("HomePageMediaBodyFourDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEST PRICE GUARANTEE.
        /// </summary>
        public static string HomePageMediaBodyFourHeader {
            get {
                return ResourceManager.GetString("HomePageMediaBodyFourHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect destination in Egypt : Hurghada / Luxor and Cairo.
        /// </summary>
        public static string HomePageMediaBodyOneDesc {
            get {
                return ResourceManager.GetString("HomePageMediaBodyOneDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 PARADISE DESTINATION.
        /// </summary>
        public static string HomePageMediaBodyOneHeader {
            get {
                return ResourceManager.GetString("HomePageMediaBodyOneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are here to help, before, during, and even after your trip..
        /// </summary>
        public static string HomePageMediaBodyThreeDesc {
            get {
                return ResourceManager.GetString("HomePageMediaBodyThreeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP NOTCH SUPPORT.
        /// </summary>
        public static string HomePageMediaBodyThreeHeader {
            get {
                return ResourceManager.GetString("HomePageMediaBodyThreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online-Service für 24 x 7.
        /// </summary>
        public static string HomePageMediaBodyTwoDesc {
            get {
                return ResourceManager.GetString("HomePageMediaBodyTwoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 X 7-SERVICE.
        /// </summary>
        public static string HomePageMediaBodyTwoHeader {
            get {
                return ResourceManager.GetString("HomePageMediaBodyTwoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min price.
        /// </summary>
        public static string HomePageMinPrice {
            get {
                return ResourceManager.GetString("HomePageMinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu Ausflüge.
        /// </summary>
        public static string HomePageNewTour {
            get {
                return ResourceManager.GetString("HomePageNewTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SONDERANGEBOT.
        /// </summary>
        public static string HomePageOffer {
            get {
                return ResourceManager.GetString("HomePageOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie Ihre Tour aus.
        /// </summary>
        public static string HomePageSelectTour {
            get {
                return ResourceManager.GetString("HomePageSelectTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to our Articals.
        /// </summary>
        public static string HomePageSubTitelArticals {
            get {
                return ResourceManager.GetString("HomePageSubTitelArticals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOUREN-TRENDS.
        /// </summary>
        public static string HomePageTerends {
            get {
                return ResourceManager.GetString("HomePageTerends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome to Royal Route.
        /// </summary>
        public static string HomePageTitel {
            get {
                return ResourceManager.GetString("HomePageTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POPULAR TOUR.
        /// </summary>
        public static string HomePageTitelPopoulerTour {
            get {
                return ResourceManager.GetString("HomePageTitelPopoulerTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2022.
        /// </summary>
        public static string HomePageYear {
            get {
                return ResourceManager.GetString("HomePageYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to im Angebot.
        /// </summary>
        public static string OnSale {
            get {
                return ResourceManager.GetString("OnSale", resourceCulture);
            }
        }
    }
}
